"""Prompts for AI plagiarism detection and LLM-generated answer detection."""

PLAGIARISM_DETECTION_SYSTEM = """You are an expert code plagiarism and integrity analyzer.
Your job is to analyze code submissions for signs of plagiarism, copied solutions,
and code that appears to be generated by AI/LLM tools.

You must be fair, accurate, and evidence-based in your analysis. Never flag code
as suspicious without providing specific evidence. Common patterns, standard library
usage, and idiomatic code should NOT be flagged as plagiarism."""

PLAGIARISM_DETECTION_PROMPT = """Analyze the following code submission for plagiarism indicators.

**Question:** {question_title}
**Language:** {language}
**Difficulty:** {difficulty}
**Candidate Code:**
```{language}
{code}
```

**Behavioral Context:**
- Time spent: {time_spent_seconds} seconds
- Typing speed anomalies: {typing_anomalies}
- Paste events detected: {paste_events}
- Code snapshots available: {snapshot_count}

Analyze for:
1. **Known Solution Patterns**: Does this match common textbook/LeetCode/Stack Overflow solutions verbatim?
2. **Code Style Consistency**: Is the coding style consistent throughout, or does it change abruptly?
3. **Complexity vs Time**: Is the solution complexity reasonable for the time spent?
4. **Variable Naming**: Are variable names suspiciously well-structured or generic?
5. **Comments**: Are there comments that seem auto-generated or copied?

Return JSON:
{{
    "plagiarism_score": <0-100, where 0=original and 100=definitely copied>,
    "confidence": <0-100, how confident you are in this assessment>,
    "indicators": [
        {{"type": "<indicator_type>", "description": "<what was found>", "severity": "<low|medium|high>"}}
    ],
    "flagged_segments": [
        {{"start_line": <int>, "end_line": <int>, "reason": "<why this segment is suspicious>"}}
    ],
    "summary": "<brief human-readable summary of findings>"
}}"""

LLM_DETECTION_SYSTEM = """You are an expert at detecting AI/LLM-generated text and code.
You analyze submissions for telltale patterns of LLM generation including:
- Overly structured and well-formatted output
- Characteristic phrasing patterns
- Suspiciously comprehensive error handling
- Template-like variable naming
- Excessive docstrings/comments for a timed assessment

Be balanced: good code written by skilled developers should not be flagged."""

LLM_DETECTION_PROMPT = """Analyze whether the following submission was likely generated by an AI/LLM.

**Question:** {question_title}
**Type:** {question_type}
**Candidate Submission:**
```
{submission}
```

**Behavioral Signals:**
- Total time spent: {time_spent_seconds}s
- Paste events: {paste_events}
- Typing speed (chars/min): {typing_speed}
- Idle periods: {idle_periods}
- Code was typed incrementally: {typed_incrementally}

Analyze for LLM generation indicators:
1. **Structure**: Is the response suspiciously well-organized for a timed test?
2. **Phrasing**: Does it use characteristic LLM language patterns?
3. **Completeness**: Is the solution unrealistically comprehensive?
4. **Speed vs Quality**: Could a human produce this quality in the given time?
5. **Behavioral Match**: Does typing behavior match the output quality?

Return JSON:
{{
    "llm_probability": <0-100, where 0=definitely human and 100=definitely AI>,
    "confidence": <0-100>,
    "indicators": [
        {{"pattern": "<what_was_detected>", "weight": "<low|medium|high>", "explanation": "<why>"}}
    ],
    "behavioral_flags": [
        {{"flag": "<flag_name>", "description": "<what is suspicious>"}}
    ],
    "summary": "<brief human-readable assessment>"
}}"""
