"""LLM Answer Detector Agent — detects AI-generated text and code."""

import logging
from typing import Any

from app.ai.providers.factory import get_ai_provider
from app.ai.prompts.plagiarism_prompts import (
    LLM_DETECTION_SYSTEM,
    LLM_DETECTION_PROMPT,
)

logger = logging.getLogger(__name__)


class LLMAnswerDetectorAgent:
    """Detects whether submissions were generated by AI/LLM tools."""

    def __init__(self, provider_name: str | None = None):
        self.provider = get_ai_provider(provider_name)

    async def analyze(
        self,
        question_title: str,
        question_type: str,
        submission: str,
        time_spent_seconds: int = 0,
        paste_events: int = 0,
        typing_speed: float = 0.0,
        idle_periods: int = 0,
        typed_incrementally: bool = True,
    ) -> dict[str, Any]:
        """Analyze a submission for LLM generation indicators.

        Returns:
            Dict with llm_probability, confidence, indicators, behavioral_flags, summary.
        """
        prompt = LLM_DETECTION_PROMPT.format(
            question_title=question_title,
            question_type=question_type,
            submission=submission[:3000],
            time_spent_seconds=time_spent_seconds,
            paste_events=paste_events,
            typing_speed=f"{typing_speed:.1f}",
            idle_periods=idle_periods,
            typed_incrementally="yes" if typed_incrementally else "no",
        )

        try:
            result = await self.provider.complete_structured(
                prompt=prompt,
                system_prompt=LLM_DETECTION_SYSTEM,
                temperature=0.2,
                max_tokens=2000,
            )
        except Exception as e:
            logger.error("LLM detection failed: %s", e)
            return {
                "llm_probability": 0,
                "confidence": 0,
                "indicators": [],
                "behavioral_flags": [],
                "summary": "Analysis unavailable",
            }

        # Bound scores
        result["llm_probability"] = max(0, min(float(result.get("llm_probability", 0)), 100))
        result["confidence"] = max(0, min(float(result.get("confidence", 0)), 100))

        return result
